
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/0.2/output.jpg C:\gitedit\appleDX/Gamma1/0.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/0.4/output.jpg C:\gitedit\appleDX/Gamma1/0.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/0.6/output.jpg C:\gitedit\appleDX/Gamma1/0.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/0.8/output.jpg C:\gitedit\appleDX/Gamma1/0.8/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/1.0/output.jpg C:\gitedit\appleDX/Gamma1/1.0/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/1.2/output.jpg C:\gitedit\appleDX/Gamma1/1.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/1.4/output.jpg C:\gitedit\appleDX/Gamma1/1.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/1.6/output.jpg C:\gitedit\appleDX/Gamma1/1.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/Gamma1/1.8/output.jpg C:\gitedit\appleDX/Gamma1/1.8/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/0.2/output.bmp C:\gitedit\appleDX/gamma2/0.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/0.4/output.bmp C:\gitedit\appleDX/gamma2/0.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/0.6/output.bmp C:\gitedit\appleDX/gamma2/0.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/0.8/output.bmp C:\gitedit\appleDX/gamma2/0.8/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/1.0/output.bmp C:\gitedit\appleDX/gamma2/1.0/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/1.2/output.bmp C:\gitedit\appleDX/gamma2/1.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/1.4/output.bmp C:\gitedit\appleDX/gamma2/1.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/1.6/output.bmp C:\gitedit\appleDX/gamma2/1.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma2/1.8/output.bmp C:\gitedit\appleDX/gamma2/1.8/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/0.2/output.bmp C:\gitedit\appleDX/gamma3/0.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/0.4/output.bmp C:\gitedit\appleDX/gamma3/0.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/0.6/output.bmp C:\gitedit\appleDX/gamma3/0.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/0.8/output.bmp C:\gitedit\appleDX/gamma3/0.8/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/1.0/output.bmp C:\gitedit\appleDX/gamma3/1.0/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/1.2/output.bmp C:\gitedit\appleDX/gamma3/1.2/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/1.4/output.bmp C:\gitedit\appleDX/gamma3/1.4/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/1.6/output.bmp C:\gitedit\appleDX/gamma3/1.6/conv_RBF.txt
convert_color.exe hanabi_def.jpg C:\gitedit\appleDX/gamma3/1.8/output.bmp C:\gitedit\appleDX/gamma3/1.8/conv_RBF.txt
